---
title: "TP bourdon"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
SciViews::R
```


```{r read}
colonie <- read("bourdonR.xlsx")
```

```{r mutate larve}
colonie %>.% 
  filter(., Type == "larve") %>.%
  select(., -ITD) %>.% 
  mutate(., t_m = taille/masse) %>.% 
  labelise(., self = FALSE, label = list(t_m = "Rapport largeur-poids"), units = list(t_m = "mm/g"))-> colonie_larve
```

```{r dénombrement larve}
chart(data = colonie_larve, ~t_m)+ 
  geom_histogram(bins = 40) +
  ylab("Dénombrement")
```

```{r mutate ouvrière}
colonie %>.% 
  filter(., Type != "oeufs") %>.%
  filter(., Type != "larve") %>.%
  filter(., Type != "pupe") %>.%
  filter(., Type != "pas encore emergé") %>.%
  select(., -taille) %>.% 
  mutate(., t_m = ITD/masse) %>.% 
  labelise(., self = FALSE, label = list(t_m = "Rapport ITD-poids"), units = list(t_m = "mm/g"))-> colonie_ouvrière
```

```{r dénombrement ouvrière}
chart(data = colonie_ouvrière, ~t_m)+ 
  geom_histogram(bins = 40) +
  ylab("Dénombrement") 
```
```{r denomb larve taille}
chart(data = colonie_larve, ~taille)+ 
  geom_histogram(bins = 40) +
  ylab("Dénombrement") + 
  xlab ("Largeur (cm)")
```

```{r denomb larve masse}
chart(data = colonie_larve, ~masse)+ 
  geom_histogram(bins = 30) +
  ylab("Dénombrement")
```

```{r denomb ouvrière taille}
chart(data = colonie_ouvrière, ~ITD)+ 
  geom_histogram(bins = 50) +
  ylab("Dénombrement") + 
  xlab ("ITD (mm)")
```

```{r denomb larve masse}
chart(data = colonie_ouvrière, ~masse)+ 
  geom_histogram(bins = 40) +
  ylab("Dénombrement")
```
